support remote testnets (read only)

diff --git a/libexec/mcd/mcd b/libexec/mcd/mcd
--- a/libexec/mcd/mcd
+++ b/libexec/mcd/mcd
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
 ### McDai - Multi-collateral Dai
+shopt -s extglob
 
 OPTS="mcd [<options>] <command> [<args>]
 mcd [<command>] --help
 --
   Connection options:
-C,chain=chain         chain config - kovan , mainnet, or rpc testnet
+C,chain=chain         chain config - mainnet, kovan, testnet or a remote testnet id
 
   Transaction Options:
 F,from=address        account to send from
@@ -56,33 +57,47 @@ while [[ $1 ]]; do
   esac; shift
 done
 
-export_config() {
-  conf=${MCD_CONFIG:-$1}
-  [[ ! -f "$conf" ]] && echo "File not found: $conf" && exit 1
-  entries=$(cat $conf | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]")
-  for e in $entries; do export "$e"; done
+require-chain() {
+  chain=${MCD_CONFIG:-$1}
+  path=${0%/*}/conf/$chain.json;
+
+  if [[ ! -e "$path" ]]; then
+    id=${chain%-testnet}
+    conf=$(mcd -C skip testnet chain ${id} | jq '.')
+    if [[ "$conf" == "null" ]]; then
+      echo "Error: chain config not found for $id"
+      exit 1
+    else
+      echo $conf > $path
+    fi
+  fi
+
+  exports=$(cat $path | jq -rc ".deploy_data // . | \
+    to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]")
+  for e in $exports; do export "$e"; done
 }
 
 case "$MCD_CHAIN" in
   mainnet)
+    require-chain mainnet
     export SETH_CHAIN=mainnet
-    export ETH_LOGS_API=etherscan
-    export ETHERSCAN_API_URL=https://api.etherscan.io/api
-    export_config ${0%/*}/conf/mainnet.json;
     ;;
-  testnet)
+  testnet) # local testnet
+    require-chain "$MCD_CONFIG"
     export ETH_RPC_URL=http://127.0.0.1:8545
     export ETH_LOGS_API=rpc
     export ETH_KEYSTORE=~/.dapp/testnet/8545/keystore
     export ETH_PASSWORD=${0%/*}/conf/testnet.pw
     export ETH_FROM=$(seth accounts ls | sed 1q | awk '{print substr ($0, 0, 42)}')
-    export_config ~/.dapp/testnet/8545/config/addresses.json;
     ;;
-  *) # default to kovan
+  skip) { echo; };;
+  +([0-9])) # remote testnet id
+    require-chain "$MCD_CHAIN-testnet"
+    [[ -e $path ]] && export ETH_RPC_URL=$(cat $path | jq -r .chain_details.rpc_url)
+    ;;
+  *)
+    require-chain kovan
     export SETH_CHAIN=kovan
-    export ETH_LOGS_API=etherscan
-    export ETHERSCAN_API_URL=https://api-kovan.etherscan.io/api
-    export_config ${0%/*}/conf/kovan.json
     ;;
 esac
 
