only allow valid ilk identifiers

diff --git a/libexec/mcd/mcd---fail b/libexec/mcd/mcd---fail
--- a/libexec/mcd/mcd---fail
+++ b/libexec/mcd/mcd---fail
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 err=${1##*/}
 act=${err%\:*}
-echo "Error: ${err#*\:}"; echo
+echo "Error:${err#*\:}" >&2; echo >&2
 mcd >&2 ${act#*-} --help
 exit 1
diff --git a/libexec/mcd/mcd---require-ilk b/libexec/mcd/mcd---require-ilk
--- a/libexec/mcd/mcd---require-ilk
+++ b/libexec/mcd/mcd---require-ilk
@@ -1,4 +1,21 @@
 #!/usr/bin/env bash
 set -e
+
 [ -n "$MCD_ILK" ] || mcd --fail "$1: Missing Ilk identifier"
+
+invalid-ilk() {
+  echo "Error: invalid Ilk identifier - $MCD_ILK" >&2
+  echo "Valid Ilks:" >&2
+  mcd ilks >&2
+  exit 1
+}
+
+for id in $(mcd ilks | cut -d ' ' -f 1); do
+  if [ "$MCD_ILK" == "$id" ]; then
+    valid=true
+  fi
+done
+
+[ "$valid" = true ] || invalid-ilk
+
 echo $(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
