Fail message

diff --git a/libexec/mcd/mcd-exit b/libexec/mcd/mcd-exit
--- a/libexec/mcd/mcd-exit
+++ b/libexec/mcd/mcd-exit
@@ -2,14 +2,14 @@
 ### mcd-exit -- Remove collateral from the system
 ### Usage: mcd exit <adapter-address> <amount>
 set -e
-[ $# = 2 ] || mcd exit --fail
+[ $# = 2 ] || mcd --fail "$0: Missing argument(s)"
 
 # TODO - check inputs
-# TODO - adapter dictionary
 
-echo >&2 "Withdrawing $2 GEM"
-
-lad=$(seth --to-address $1)
+lad=$(seth --to-address $1) || mcd --fail "$0: Invalid adapter address $1"
 wad=$(seth --to-hex $(seth --to-wei "$2 eth"))
+
+# TODO - adapter dictionary
+echo >&2 "Withdrawing $2 GEM"
 
 (set -x; seth send "${lad}" "exit(uint)" "$wad")
