bite

diff --git a/libexec/mcd/mcd-bite b/libexec/mcd/mcd-bite
--- a/libexec/mcd/mcd-bite
+++ b/libexec/mcd/mcd-bite
@@ -11,6 +11,31 @@ set -e
 mcd --fail "$0: Missing argument(s)"
 
 ilk=$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
-urn=$(seth --to-bytes32 $MCD_URN)
+urn=$(seth --to-word $(seth --to-address $MCD_URN))
 
-(set -x; seth send "${MCD_CAT}" "bite(bytes32,bytes32)(uint256)" "$ilk" "$urn")
+echo >&2 "Biting urn..."
+
+tx=$(seth send --async "${MCD_CAT}" "bite(bytes32,bytes32)(uint256)" "$ilk" "$urn")
+echo >&2 -n "Waiting for transaction receipt..."
+number=$(SETH_TICK=true seth receipt "$tx" blockNumber)
+number=$(seth --to-hex "$number")
+echo >&2
+sig=$(seth keccak "$(seth --from-ascii 'Bite(bytes32,bytes32,uint256,uint256,uint256,uint256,uint256)')")
+logs=$(seth rpc eth_getLogs -- -n {} -s "${MCD_CAT?}" -i address \
+                                     -s "$number"  -i fromBlock \
+                                     -s "$number"  -i toBlock \
+                               -n [] -s "$sig"     -i append \
+                                     -i topics \
+                                     -i append | echo "[$(paste -sd , -)]")
+data=$(echo "$logs" | jshon -a -e data -u)
+hash=$(echo "$logs" | jshon -a -e transactionHash -u)
+
+if [ "$hash" == "$tx" ]; then
+  echo "flip: $(seth --to-dec 0x${data:196:64})"
+  echo "ink: $(mcd wad ${data:2:64})"
+  echo "art: $(mcd wad ${data:66:64})"
+  echo "tab: $(mcd wad ${data:130:64})"
+else
+  echo "Bite - failed trasaction: $tx"
+  mcd urn
+fi
