event timestamps

diff --git a/libexec/mcd/mcd---events b/libexec/mcd/mcd---events
--- a/libexec/mcd/mcd---events
+++ b/libexec/mcd/mcd---events
@@ -1,19 +1,27 @@
 #!/usr/bin/env bash
-set -e
+ETH_BLOCK=${ETH_BLOCK:-earliest}
+
+params=(
+  "module=logs" "action=getLogs"
+  "address=$1" "fromBlock=$ETH_BLOCK" "toBlock=latest"
+  "apikey=$ETHERSCAN_API_KEY"
+)
+
+[[ ! -z "$2" ]] && params[7]="topic0=$2"
 
 if [ ! -z "$MCD_ILK" ]; then
   ilk=0x$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
-  topics="-s $2 -i append -s $ilk -i append"
+  params[8]="topic0_1_opr=and"
+  params[9]="topic1=$ilk"
+fi
+
+query=$(printf "&%s" "${params[@]}")
+response=$(seth curl "${ETHERSCAN_API_URL?}""${query/&/?}")
+message=$(jshon <<<"$response" -e message -u)
+result=$(jshon <<<"$response" -e result -j)
+if [[ $message = OK || $result = "[]" ]]; then
+  jshon <<<"$result" -a -j
 else
-  topics="-s $2 -i append"
+  echo >&2 "${0##*/}: error: $response"
+  exit 1
 fi
-
-if [ ! -z "$ETH_BLOCK" ]; then
-  ETH_BLOCK=$(seth --to-hex $ETH_BLOCK)
-fi
-ETH_BLOCK=${ETH_BLOCK:-earliest}
-
-seth rpc eth_getLogs -- \
-  -n {} -s $(seth --to-address "$1") -i address \
-        -s $ETH_BLOCK -i fromBlock \
-  -n [] $topics -i topics -i append
