gem join & exit

diff --git a/libexec/mcd/mcd-gem b/libexec/mcd/mcd-gem
--- a/libexec/mcd/mcd-gem
+++ b/libexec/mcd/mcd-gem
@@ -1,9 +1,20 @@
 #!/usr/bin/env bash
 ### mcd-gem -- Gem balances
 ### Usage: mcd gem --ilk=<id> [<command>]
+###
+### Commands: balance [<address>]
+###           join <wad>
+###           exit <wad>
+###
+### With `balance' get gem balances for a given address (default: ETH_FROM).
+### With `join' add collateral to the system.
+### With `exit' remove collateral from the system.
+###
+### Example: mcd --ilk=ETH gem balance
+###          mcd --ilk=ETH gem join 42
 set -e
 
-[ ! -z "$MCD_ILK" ] || mcd --fail "$0: Missing argument(s)"
+[ ! -z "$MCD_ILK" ] || mcd --fail "$0: Missing Ilk identifier"
 ilk=$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
 
 case $1 in
@@ -16,20 +27,13 @@ case $1 in
     echo "free: $(mcd --to-rad $gem)"
     echo "total: $(bc <<< "$(mcd --to-rad $gem) + $ink")"
   };;
-  move) {
-    echo "Not implemented"
+  join) {
+    mcd gem-join $2
   };;
-  hope) {
-    echo "Not implemented"
-  };;
-  nope) {
-    echo "Not implemented"
+  exit) {
+    mcd gem-exit $2
   };;
   *) {
-    echo "Options:"
-    echo "  balance [<address>]"
-    echo "  hope <address>"
-    echo "  move <src> <dst>"
-    echo "  nope <address>"
+    mcd help gem
   }
 esac
